name: Senhaix Build

permissions:
  contents: write
  actions: write

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Build UNIVERSIAL
      shell: pwsh
      run: | 
        mkdir tmpu
        Set-TimeZone -Name "China Standard Time"
        $commitHash = git rev-parse --short HEAD
        $buildTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $tagName = git describe --tags --abbrev=0 --always || ""
        cd Properties
        $sourceFile = "./VERSION.cs"
        (Get-Content $sourceFile) `
          -replace '@COMMIT_HASH@', $commitHash `
          -replace '@BUILD_TIME@', $buildTime `
          -replace '@TAG_NAME@', $tagName `
          | Set-Content $sourceFile
        cd ..
        dotnet restore -r win-x64
        dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true /p:TargetOS=Windows --self-contained true
        cd D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/bin/Release/net6.0-windows10.0.19041.0/win-x64
        mkdir senhaix-universial-freq-writer
        mv publish/* senhaix-universial-freq-writer
        Compress-Archive -Path .\senhaix-universial-freq-writer -DestinationPath D:\a\senhaix-freq-writer-enhanced\senhaix-freq-writer-enhanced\tmpu\senhaix-universial-freq-writer-Windows-${tagName}.zip
        cd D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/
        dotnet restore -r linux-x64
        dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true --self-contained true
        cd D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/bin\Release\net6.0\linux-x64\
        mkdir senhaix-universial-freq-writer
        mv publish/* senhaix-universial-freq-writer
        Compress-Archive -Path .\senhaix-universial-freq-writer -DestinationPath D:\a\senhaix-freq-writer-enhanced\senhaix-freq-writer-enhanced\tmpu\senhaix-universial-freq-writer-Linux-${tagName}.zip
        cd D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/
        dotnet restore -r osx-x64
        dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:UseAppHost=true -property:Configuration=Release
        cd D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/bin\Release\net6.0\osx-x64\
        mkdir senhaix-universial-freq-writer
        mv D:/a/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/Asset/shx8800-icons/icon.icns publish/SenhaixFreqWriter.app/Contents/Resources
        mv publish/SenhaixFreqWriter.app senhaix-universial-freq-writer
        Compress-Archive -Path .\senhaix-universial-freq-writer -DestinationPath D:\a\senhaix-freq-writer-enhanced\senhaix-freq-writer-enhanced\tmpu\senhaix-universial-freq-writer-macOS-${tagName}.zip
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SenhaixFreqWriterArtifacts
        path: ./tmpu

  afterbuild:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        # name: SenhaixFreqWriterArtifacts
        path: ./

    - name: Delete Artifact by Name
      uses: jimschubert/delete-artifacts-action@v1
      with:
        artifact_name: SenhaixFreqWriterArtifacts
        min_bytes: '0'

    - name: Add Execute
      run: |
        ls && cd /home/runner/work/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/SenhaixFreqWriterArtifacts && targetName=$(ls  | grep senhaix-universial-freq-writer-macOS) && \
        echo $targetName && unzip $targetName && rm -rf $targetName && \
        chmod +x senhaix-universial-freq-writer/SenhaixFreqWriter.app/Contents/MacOS/SenhaixFreqWriter && \
        zip -r $targetName senhaix-universial-freq-writer && \
        rm -rf senhaix-universial-freq-writer && cd /home/runner/work/senhaix-freq-writer-enhanced/senhaix-freq-writer-enhanced/SenhaixFreqWriterArtifacts && targetName=$(ls  | grep senhaix-universial-freq-writer-Linux) && \
        echo $targetName && unzip $targetName && rm -rf $targetName && \
        chmod +x senhaix-universial-freq-writer/SenhaixFreqWriter && \
        zip -r $targetName senhaix-universial-freq-writer

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SenhaixFreqWriterArtifacts
        path: SenhaixFreqWriterArtifacts/*.zip
    
    - name: Release UNIVERSAL
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./*.zip